### PR TITLE
Autonomous Mission Calibration

### PR DESCRIPTION
**Pull request by docprofsky**
I believe the auto missions are ready to be merged. @Ben1492 @TaeSeanDo, is this ready to be merged?

### CODE REVIEW

**Comment by TaeSeanDo** [comment]
Comment out "missionRight" to avoid confusion; that one is old.

**Comment by docprofsky** [comment]
@TaeSeanDo I have added that to #36.

**Comment by TaeSeanDo** [comment]
Looks good except that it would be nice to delete the commented code. Also you should add`//The best function ever! (insert accordion here)` above the howManyRoads() function.

**Comment by docprofsky** [comment]
@TaeSeanDo I already started merging this (now finished) when you commented. These changes can be added to master as part of the work that needs to be done to clean up the code.

**Pull request merged**
